export const businessTypes = [
  { label: "Retail Store", value: "retail" },
  { label: "Wholesale Business", value: "wholesale" },
  { label: "Distributor", value: "distributor" },
  { label: "Manufacturer", value: "manufacturing" },
  { label: "E-Commerce", value: "ecommerce" },
  { label: "Service Provider", value: "service" },
  { label: "IT & Software", value: "it_software" },
  { label: "Marketing Agency", value: "marketing_agency" },
  { label: "Consultancy", value: "consultancy" },
  { label: "Education & Training", value: "education" },
  { label: "Healthcare & Clinic", value: "healthcare" },
  { label: "Real Estate", value: "real_estate" },
  { label: "Construction & Contractors", value: "construction" },
  { label: "Logistics & Transport", value: "logistics" },
  { label: "Restaurant & Cafe", value: "restaurant" },
  { label: "Travel & Tourism", value: "travel" },
  { label: "Finance & Insurance", value: "finance" },
  { label: "Other", value: "other" },
];
